package com.bartoszdrozd.mediapp.auth.models

enum class AuthErrorCode {
    GENERIC_SIGN_IN_ERROR, EMAIL_IN_USE, PASSWORD_TOO_SHORT, EMAILS_NOT_EQUAL, PASSWORDS_NOT_EQUAL, EMAIL_NOT_SET, FIRST_NAME_NOT_SET, LAST_NAME_NOT_SET, DOB_NOT_SET, CONFIRM_PASSWORD_NOT_SET, CONFIRM_EMAIL_NOT_SET, GENERIC_REGISTER_ERROR, GENDER_NOT_SET
}